# Generated by Django 5.1.1 on 2024-09-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('communityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('iconURL', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convo',
            fields=[
                ('convoID', models.AutoField(primary_key=True, serialize=False)),
                ('convoName', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('displayName', models.CharField(blank=True, max_length=20)),
                ('profilePicture', models.CharField(blank=True, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('backgroundColor', models.CharField(blank=True, max_length=7)),
                ('backgroundImage', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('hasEdit', models.BooleanField(default=False)),
                ('editDate', models.DateTimeField(null=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaID', models.AutoField(primary_key=True, serialize=False)),
                ('mediaType', models.IntegerField()),
                ('mediaURL', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('commentContent', models.CharField(max_length=255)),
                ('hasEdit', models.BooleanField(default=False)),
                ('editDate', models.DateTimeField(null=True)),
                ('replyTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('voteID', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('messageDate', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.convo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='database.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friendShipID', models.AutoField(primary_key=True, serialize=False)),
                ('friendDate', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='database.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConvoSetting',
            fields=[
                ('settingID', models.AutoField(primary_key=True, serialize=False)),
                ('isMuted', models.BooleanField(default=False)),
                ('isPinned', models.BooleanField(default=False)),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.convo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConvoParticipant',
            fields=[
                ('participantID', models.AutoField(primary_key=True, serialize=False)),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.convo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('membershipID', models.AutoField(primary_key=True, serialize=False)),
                ('joinDate', models.DateTimeField(auto_now_add=True)),
                ('role', models.IntegerField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('voteID', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
